#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\atakspel.bof
BOFS = boltspel.bof shokfury.bof exfrost.bof blasfire.bof splsacid.bof vampdrn.bof \
       illwound.bof earthqua.bof radproj.bof holyblaze.bof souldrn.bof \
       soulspl.bof bonebrth.bof corpexpl.bof soltheft.bof solannih.bof

!include $(KODDIR)\kod.mak
