#
# Makefile for compiling the Blakod - Silver Light Haven NPCs
#

!include $(TOPDIR)\common.mak

DEPEND = ..\sltwn.bof
BOFS  = slapoth.bof saura.bof ugor.bof grelda.bof tarien.bof fenric.bof hennainnk.bof

!include $(KODDIR)\kod.mak
