#
# Makefile for compiling the Blakod - Tower of Quests and Fights
#

!include $(TOPDIR)\common.mak

DEPEND = ..\towerroom.bof

BOFS =  towerst1.bof towerst2.bof towerst3.bof towerst4.bof towerst5.bof \
        towerst6.bof towerst7.bof towerst8.bof towerst9.bof towerst10.bof \
        towerst11.bof towerst12.bof towerst13.bof towerst14.bof towerst15.bof


!include $(KODDIR)\kod.mak

