#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\debuff.bof
BOFS = blind.bof cursewp.bof dazzle.bof disease.bof dishonor.bof forget.bof \
       hold.bof seduce.bof vertigo.bof spctchl.bof gravgrip.bof dthfever.bof \
       ghstmark.bof solchain.bof crsweak.bof solshack.bof

!include $(KODDIR)\kod.mak
